### ISSUE TITLE
Download counter

### ISSUE THREAD

**Issue by maldboy** [ticktackk/ResourceManagerStatsWidgetForXF2#2]
Download counter haven't changed from the day i installed the addon.Any thoughts?

**Comment by ticktackk** [comment]
Seems to be working fine for me. Make sure "Update view counters" cron is running as expected or else the view count for attachments associated with resource versions will not be updated.

**Comment by maldboy** [comment]
Update view counters & XFRM: Update view counters crons are both there and running, thread and resource views are working fine.

**Comment by maldboy** [comment]
other counters are working from the addon, only the download counter is not working

**Comment by ticktackk** [comment]
What version of XF and XFRM are you using?

**Comment by maldboy** [comment]
> What version of XF and XFRM are you using?

i'm using XF 2.2.1 & XFRM 2.2.0

**Comment by ticktackk** [comment]
Could you message me admin account details (with permission to manage crons), forum URL and XF license verification code at xenforo.com so I can look into this?

**Comment by maldboy** [comment]
Hmmm it add 2 more downloads, as i understand it counts how many different users downloaded and not how many time resources are downloaded.
